name: PR Packer
# Controls when the workflow will run
on:
  workflow_dispatch: 
  pull_request:
    branches: [ master ]
    paths: 
      - 'config/packer.json'
      - 'projects/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20

      - name: Check changed path on 1.16
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-116
        with:
          paths: projects/1.16

      - name: Check changed path on 1.16 fabric
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-116-fabric
        with:
          paths: projects/1.16-fabric
          
      - name: Check changed path on 1.18
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-118
        with:
          paths: projects/1.18

      - name: Check changed path on 1.18 fabric
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-118-fabric
        with:
          paths: projects/1.18-fabric
          
      - name: Check changed path on 1.19
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-119
        with:
          paths: projects/1.19

      - name: Check changed path on 1.19 fabric
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-119-fabric
        with:
          paths: projects/1.19-fabric

      - name: Build Packer
        run: dotnet publish .\src\Packer\Packer.csproj -o ./ -r win-x64 -p:PublishSingleFile=true

      - name: Run Packer (1.16)
        run: ./Packer --version="1.16"
        if: steps.changed-116.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        
      - name: Run Packer (1.16 Fabric)
        run: ./Packer --version="1.16-fabric"
        if: steps.changed-116-fabric.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        
      - name: Run Packer (1.18)
        run: ./Packer --version="1.18"
        if: steps.changed-118.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        
      - name: Run Packer (1.18 Fabric)
        run: ./Packer --version="1.18-fabric"
        if: steps.changed-118-fabric.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
      
      - name: Run Packer (1.19)
        run: ./Packer --version="1.19"
        if: steps.changed-119.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        
      - name: Run Packer (1.19 Fabric)
        run: ./Packer --version="1.19-fabric"
        if: steps.changed-119-fabric.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'

      - name: Create timestamp
        id: create_timestamp
        run: echo "::set-output name=timestamp::$(date '+%Y%m%d%H%M%s')"
        shell: bash

     # 额 要两分半才能传完 然而 GitHub actions 直接传的话 会压成 zip 内套 zip 就这样了吧 --cy
      - name: Unzip Files
        run:  |
          unzip -q SodiumTranslationPack-1.16.zip -d SodiumTranslationPack-1.16 || echo 0
          unzip -q SodiumTranslationPack-1.18.zip -d SodiumTranslationPack-1.18 || echo 0
          unzip -q SodiumTranslationPack-1.19.zip -d SodiumTranslationPack-1.19 || echo 0
          unzip -q SodiumTranslationPack-1.16-fabric.zip -d SodiumTranslationPack-1.16-fabric || echo 0
          unzip -q SodiumTranslationPack-1.18-fabric.zip -d SodiumTranslationPack-1.18-fabric || echo 0
          unzip -q SodiumTranslationPack-1.19-fabric.zip -d SodiumTranslationPack-1.19-fabric || echo 0
        shell: bash
          
      - name: Upload Artifact 1.16
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SodiumTranslationPack-1.16
          path: SodiumTranslationPack-1.16/*
        if: steps.changed-116.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        
      - name: Upload Artifact 1.16 fabric
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SodiumTranslationPack-1.16-fabric
          path: SodiumTranslationPack-1.16-fabric/*
        if: steps.changed-116-fabric.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        
      - name: Upload Artifact 1.18
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SodiumTranslationPack-1.18
          path: SodiumTranslationPack-1.18/*
        if: steps.changed-118.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        
      - name: Upload Artifact 1.18 fabric
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SodiumTranslationPack-1.18-fabric
          path: SodiumTranslationPack-1.18-fabric/*
        if: steps.changed-118-fabric.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'

       - name: Upload Artifact 1.19
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SodiumTranslationPack-1.19
          path: SodiumTranslationPack-1.19/*
        if: steps.changed-119.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        
      - name: Upload Artifact 1.19 fabric
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SodiumTranslationPack-1.19-fabric
          path: SodiumTranslationPack-1.19-fabric/*
        if: steps.changed-119-fabric.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'